Revert "Improve secure temp directory creation"
This reverts commit 278e168cd842454a71315c8f75a4d4b1eab4c9d7.

The m4 approach is not as portable as I first thought. Even recent OS
X versions are running a version of m4 too old for this trick.

The Bash FAQ breaks down _why_ the random name approach is secure:

> You're relying on the atomicity of mkdir for your security, not the
> obscurity of your random name.
>
> — https://mywiki.wooledge.org/BashFAQ/062

So we should add an exit code check here as well.

diff --git a/bin/new-sh b/bin/new-sh
--- a/bin/new-sh
+++ b/bin/new-sh
@@ -32,8 +32,8 @@ test "$lang" = 'sh' && cat >> "$script" <<-'EOS'
 
 NAME=$(basename "$0")
 VERSION='0.0.1'
-TEMP=$(printf 'mkstemp(template)\n' |
-    m4 -D template="${TMPDIR:-/tmp}/${NAME}XXXXXX")
+TEMP="${TMPDIR-/tmp}/${NAME}.${$}.$(awk \
+    'BEGIN {srand(); printf "%d\n", rand() * 10^10}')"
 
 help () {
     # Extract contiguous lines of comments in a function as help text
@@ -95,6 +95,12 @@ _main () {
         esac
     done
     shift $(( OPTIND - 1 ))
+
+    mkdir -p -m 700 "$TEMP"
+    if [ $? -ne 0 ]; then
+        printf 'Error creating temp directory.\n' 1>&2
+        exit 1
+    fi
 
     cmd="${1:?"No command given.
 
